apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: chatbot-icp
  name: chatbot-icp
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.PORT }}
    targetPort: bot-port
  selector:
    app: chatbot-icp

