apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chatbot-icp
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: chatbot-icp
          servicePort: 8044
      - path: /status
        backend:
          serviceName: chatbot-icp
          servicePort: 8044