apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: chatbot-icp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    soltution: mynw-app-mcm
  name: chatbot-icp
status: {}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chatbot-icp
        role: service
        soltution: mynw-app-mcm
    spec:
      imagePullSecrets:
        - name: regsecret-chatbot
      restartPolicy: Always
      containers:
      - args:
        - npm
        - run
        - start:bot
        image: "{{ .Values.image_repository }}:{{ .Values.image_tag }}"
        imagePullPolicy: Always
        name: chatbot-icp
        livenessProbe:
          timeoutSeconds: 2
          initialDelaySeconds: 65
          periodSeconds: 15
          httpGet:
            path: /status?deps=true
            port: bot-port
        ports:
        - name: bot-port
          containerPort: {{ .Values.PORT }}
        resources: {}
        workingDir: /app
        env:
{{ toYaml .Values.envVariables | indent 10 }}
