apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gateway-icp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: gateway-icp
status: {}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway-icp
        role: service
    spec:
      imagePullSecrets:
        - name: regsecret-chatbot
      restartPolicy: Always
      containers:
      - args:
        - npm
        - run
        - start:gateway
        image: "{{ .Values.image_repository }}:{{ .Values.image_tag }}"
        imagePullPolicy: Always
        name: gateway-icp
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 15
          httpGet:
            path: /status
            port: gateway-port
        ports:
        - name: gateway-port
          containerPort: {{ .Values.PORT }}
        resources: {}
        workingDir: /app
        env:
{{ toYaml .Values.envVariables | indent 10 }}
