apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ipc-monitoring
  labels:
    versionNo: 0.0.7
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: monitoring-icp
        solution: mynw-app-mcm
        tier: backend
        track: stable
        role: web
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
        - name: moniotoring-image-icp
          image: i038180458258.dkr.ecr.eu-west-1.amazonaws.com/monitoring
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: TARGET_ENV
              value: dev
