dependencies:
- name: redis
  path: ./charts/redis
  version: 1.1.11
  condition: redis.enabled
- name: bot
  path: ./charts/bot
  version: 0.1.0
  condition: bot.enabled
- name: gateway
  path: ./charts/gateway
  version: 0.1.0
  condition: gateway.enabled