apiVersion: mcm.ibm.com/v1alpha1
kind: Application
metadata:
  name: mynw-app
  labels:
    app: mynw-app
    chart: mynw-app-0.0.1
    release: mynw-app
    name: mynw-app
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mynw-monitoring
      - mynw-creds
  componentKinds:
  - group: core
    kind: Pods
