apiVersion: mcm.ibm.com/v1alpha1
kind: Application
metadata:
  name: mynw-app
  labels:
    app: mynw-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: mynw-app
    name: mynw-app
    deployable: mynw-monitoring
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mynw-app
      - creds-icp
      - monitoring-icp
      - chatbot-icp
    - key: solution
      operator: In
      values:
      - mynw-app-mcm
  componentKinds:
  - group: core
    kind: Pods
