apiVersion: mcm.ibm.com/v1alpha1
kind: Application
metadata:
  name: mynw-app
  labels:
    app: mynw-app
    chart: mynw-app-0.0.7
    release: mynw-app
    name: mynw-app
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mynw-app
      - creds-icp
      - monitoring-icp
      - chatbot-icp
      - gateway-icp
      - redis-icp
    - key: solution
      operator: In
      values:
      - mynw-app-mcm
  componentKinds:
  - group: core
    kind: Pods
