apiVersion: mcm.ibm.com/v1alpha1
kind: Application
metadata:
  name: mynw-app
  labels:
    app: mynw-app
    chart: mynw-app-0.0.1
    release: mynw-app
    name: mynw-app
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mynw-monitoring-deployable
      - mynw-monitoring-pp
    - key: solution
      operator: In
      values:
      - monitoring-mcm
  componentKinds:
  - group: core
    kind: Pods
