apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: mynw-chatbot 
  labels:
    app: mynw-app
    chart: mynw-chatbot-0.0.1
    release: mynw-chatbot
    soltution: mynw-app-mcm
spec:
  destination:
    kind: Deployable
    name: mynw-chatbot
  type: usesCreated
  source:
    kind: Deployable
    name: mynw-monitoring
