apiVersion: mcm.ibm.com/v1alpha1
kind: ApplicationRelationship
metadata:
  name: mynw-gateway
  labels:
    app: mynw-app
    chart: mynw-gateway-0.0.2
    release: mynw-gateway
    solution: mynw-app-mcm
spec:
  destination:
    kind: Deployable
    name: mynw-gateway
  type: usesCreated
  source:
    kind: Deployable
    name: mynw-monitoring
