apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: mynw-app-pp
  labels:
    name: mynw-app
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    hcmappname: "app"
    app: mynw-app
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    solution: mynw-app-mcm
    servicekind: CacheService
spec:
  replicas: {{ .Values.replicaCount }}
  clusterSelector:
    matchLabels:
{{ toYaml .Values.targetCluster.labelSelector.matchLabels | indent 6 }}
  resourceSelector:
{{ toYaml .Values.targetCluster.resourceSelector | indent 4 }}
