apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: mynw-app-pp
  labels:
    name: mynw-app
    chart: mynw-app-0.1.3
    hcmappname: "app"
    app: mynw-app
    release: mynw-app
    heritage: mynw-app
    solution: mynw-app-mcm
    servicekind: CacheService
spec:
  replicas: 2
  clusterSelector:
    matchLabels:
     environment: Dev
     datacenter: toronto
     owner: marketing
  resourceSelector:
    type: cpu
    order: desc
