apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementPolicy
metadata:
  name: mynw-creds-pp
  labels:
    name: mynw-creds-pp
    hcmappname: "creds"
spec:
  replicas: 1
  clusterSelector:
    matchLabels:
     environment: Dev
     datacenter: toronto
  resourceSelector:
    type: cpu
    order: desc
