{{- if .Values.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: redis-icp
  labels:
    app: redis-icp
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    solution: mynw-app-mcm
type: Opaque
data:
  {{- if .Values.redisPassword }}
  redis-password: {{ .Values.redisPassword | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
